### PR TITLE
Add some margin to the right side of the radio input of questions

### PR DESCRIPTION
**Pull request by sebkur**
The answers could use some some space between the radio button and the value. How about 0.5em?

### CODE REVIEW

**Comment by sebkur** [comment]
It's possible there are other input type for which that makes sense, but you probably know better than me which ones actually appear in MapComplete

**Comment by tordans** [comment]
IMO ideally we would stick with tailwind utility classes for those things.

**Comment by sebkur** [comment]
@tordans sounds reasonable, will need to learn a bit of tailwind it appears. Are you familiar with that framework? How would you solve this particular thing?

**Comment by tordans** [comment]
> will need to learn a bit of tailwind it appears

It's worth it IMO. Great concept; but different :). https://www.youtube.com/watch?v=elgqxmdVms8&list=PL5f_mz_zU5eXWYDXHUDOLBE0scnuJofO0 is a great intro and not too long to watch.

> Are you familiar with that framework?

Yes. I am also wo suggested using it in https://github.com/pietervdvn/MapComplete/pull/183

> How would you solve this particular thing?

Instead of adding ("global") styles to a .css file, you add utility classes to the html in the JS file. 

Example: 

Bildschirmfoto 2021-05-18 um 19 29 06

**Comment by sebkur** [comment]
> Instead of adding ("global") styles to a .css file, you add utility classes to the html in the JS file.

Ah, I know that concept from Bootstrap 4 utility classes. In particular the margin styles seem to have exactly the same names.

**Comment by pietervdvn** [comment]
I kindoff built a small framework for MapComplete (well, it grew together with MC).

Most of the UI classes extend 'UIElement', which offers an 'InnerRender()' functionality generating the HTML. Every element is wrapped into a `<span>` which can be styled with `.setClass` (ideal for tailwind classes) and `.setStyle` (if something peculiar is needed).

In this case, you could add `this.setClass("mr-2")` somewhere around [here](https://github.com/pietervdvn/MapComplete/blob/235ad2cf215b0dd65f835e1fbef2545482940c10/UI/Input/RadioButton.ts#L21)

**Comment by pietervdvn** [comment]
(I should have told you from the start that this would have been better, but I was too lazy then - sorry about that)

**Pull request merged**
