### PR TITLE
chore(deps): upgrade tailwind

### PR DESCRIPTION
**Pull request by eMerzh**
Because sometimes deps need to be updated...

here is tailwind.... 

I think it didnt break too much things... but i couldn't check every popup, theme , ....

### CODE REVIEW

**Review by pietervdvn — APPROVED** [review]

**Comment by pietervdvn** [comment]
We'll see if people complain about it while using the dev version...

**Comment by pietervdvn** [comment]
Thanks for the maintainence btw!

**Comment by tordans** [comment]
We had https://github.com/pietervdvn/MapComplete/issues/851 for this and as far as I remember, some changes are needed in the config after updating. Did you check the update guide @eMerzh? One thing that stands out is, that the purge option is now "content" https://github.com/pietervdvn/MapComplete/blob/develop/tailwind.config.js#L5-L8.

**Comment by eMerzh** [comment]
@tordans yes i also saw a few deprecation warning... i'll do a followup PR

**Pull request merged**
