### PR TITLE
Spelling correction custumers/customers in Climbing theme

### PR DESCRIPTION
**Pull request by sparky-oxford**

### CODE REVIEW

**Comment by pietervdvn** [comment]
Cool!

Just a little remark: spelling and translations are handled by https://hosted.weblate.org/projects/mapcomplete/

These are pulled in regularly, and the Docs/Taginfo/* files are automatically generated from there.

**Comment by sparky-oxford** [comment]
Ahh, apologies — would you like me to make the changes there too?
Kind regards,
Mark

**Comment by pietervdvn** [comment]
No worries, what you did is correct and will be picked up by weblate too (when I merge this branch with master).

I just wanted to point out that it is easier and less work for you to make changes there ;)

**Comment by pietervdvn** [comment]
Great!

Btw, feel free to make improvements to the tagging scheme itself too ;)

**Pull request merged**
