### PR TITLE
Feature/parcel locker

### PR DESCRIPTION
**Pull request by RobinLinde**
Adds parcel lockers and splits layers, originally part of #1025.

- Renders both new and old style
- Brand (with some country-specific mappings)
- Operator
- Opening hours
- Reference number
- Mail-in + pickup question (only for new style)

### CODE REVIEW

**Comment by pietervdvn** [comment]
How did you get the 'brands' for the parcel lockers? It might be useful to parse those from the Name-Suggestion-index

**Review by pietervdvn — APPROVED** [review]

**Comment by RobinLinde** [comment]
> How did you get the 'brands' for the parcel lockers? It might be useful to parse those from the Name-Suggestion-index

Was just a small selection listed on the wiki, and some of the most common in my area.

Parsing them from the NSI would be nice, but could be complicated/interesting if more complex locationsets are used.

**Comment by RobinLinde** [comment]
Actually experimenting a bit with getting suggestions from the NSI in the charging stations theme (doesn't really work yet, but can search for suggestions).
image

**Comment by pietervdvn** [comment]
For the ID-presets, I didbexport them to a separate 'layer' from which I import the questions. Otoh, the charging stations are already generated anyway...

**Pull request merged**
