### PR TITLE
Update to HailHydrant, and minor typo fixes in other themes

### PR DESCRIPTION
**Pull request by govvin**
Here's the latest version of the HailHydrant theme.

Included in this PR are minor fixes to text in other themes.

### CODE REVIEW

**Comment by pietervdvn** [comment]
Looks good!

I thought you also created a layer with ambulance stations, but I cannot find that layer here. Did you decide to drop it after all?

**Comment by govvin** [comment]
Yes, this one should have the ambulance station layer, instead of the original rescue stations.

**Comment by pietervdvn** [comment]
Sorry, I got confused and accidentally loaded up an old version. Please ignore my previous comment. Except the looks good of course, it is a really cool theme and nice work!

**Comment by govvin** [comment]
Thanks! You've been very helpful. 

Looking forward to getting feedback, and learning more about MapComplete to further improve this theme.

**Comment by pietervdvn** [comment]
Well, the theme is live: https://mapcomplete.osm.be/hailhydrant

So, at this point, I do think you should start making some noise about your theme; write a diary entry, post to reddit, facebook, twitter, ... and get the theme to take off!

If you want more inspiration to expand the theme, maybe hospitals, police stations, doctors, pharmacies, ... Or a second, heatlh oriented theme? Whatever you feel like!

(Please note that it is relatively easy to reuse a layer between official themes - so you can make one 'hospitals.json'-layer and reuse that in e.g. 'openHealthMap' and in 'hailhaydrant'. It is also possible to override a few things in one theme to tweak it).

At last, I'm also working on some caching, so that loading can go a bit faster...

**Comment by govvin** [comment]
Great suggestions! It's been a while since my last diary entry, maybe I'll take a few minutes to write one today to help get this rolling. Thanks again, Pieter.

**Comment by pietervdvn** [comment]
Jup! I made a bit of noise to celebrate the 500th editor, that gave an uptick of around ~30 new users in the past two days - so promoting your theme definitively helps. I'm also gonna move your theme up to the second spot of the list of themes, so it is a bit more visible.

**Comment by govvin** [comment]
Yay! That'd would be awesome. :smile_cat:

**Pull request merged**
