### PR TITLE
Theme/advertising

### PR DESCRIPTION
**Pull request by paunofu**
Opening a pull request on MapComplete
=====================================

Hey! Thanks for opening a pull request on Mapcomplete! This probably means you want to add a new theme - if so, please
follow the checklist below. If this pull request is for some other issue, please ignore the template.

Adding your new theme
---------------------

Thanks for taking the time to create your theme and to add it to the main repository!

To making merging smooth, please make sure that each of the following conditions is met:

- [x] The codebase is GPL-licensed. By opening a pull request, the new theme will be GPL too
- [x] All images are included in the pull request and no images are loaded from an external service (e.g. Wikipedia)
- [x] The [guidelines on how to make your own theme](https://github.com/pietervdvn/MapComplete/blob/master/Docs/Making_Your_Own_Theme.md)
  are read and followed

Advertising theme
---------------------

With this theme you will be able to add and complete data of advertising amenities

### CODE REVIEW

**Comment by pietervdvn** [comment]
On a technical level, the theme is fine.

There however is still some finetuning to do.

# Icons

An icon for the following items is still lacking. Hopefully someone of Mastodon or Barnes38 turns up to help a bit

- [ ] flag
- [ ] screens
- [ ] sculpture
- [ ] sign
- [ ] tarp
- [ ] wall painting


# Clarifying presets

As I'm not familiar with the advertising world, it's sometimes hard to know what advertisement type is which.

For this, the presets might benefit from a `description` and in some cases `exampleImages` too. Hint: copy the descriptions from [the wiki page](https://wiki.openstreetmap.org/wiki/Key:advertising), and maybe the images too (which should be included in the repo though). An example on how to apply this in the json is [here](https://github.com/pietervdvn/MapComplete/blob/90f69bdd9378e9fecc7d32f1f308c231b24ecac9/assets/layers/bike_repair_station/bike_repair_station.json#L842)

# Animation-question

## Hiding options

The animation-question feels a bit cluttered. Furthermore, it seems that some types of animations are only relevant to some types of advertisement features.

For example, a `poster_box` will typically only be `static` or `winding_posters`.
A screen will probably be animated by itself, but I'd be very surprised to see an animated `wall_painting`.
A totem might have winding posters _or_ might rotate.

It might be useful to add to every `mapping` an `"hideInAnswer": { "and": ["advertising!=wall_poster", "advertising!=totem", ...] }` (keep in mind that you list when it should be _hidden_).

By hiding irrelevant options, the experience will be smoother.

## Phrasing

A few tweaks to the phrasing might help here as well. Instead of asking `Wich type of animation has this feature?`, asking something as `Does this feature cycle through multiple advertisements automatically?` makes the animation part more explicit.

Similarly, the answer `Yes, but without specifiying` is very confusing to see, especially if the question is not shown. Rather opt for `This advertisement feature cycles through different advertisements automatically`. This is clearer in the infobox. (Another thing: this is a very generic option. Moving it to the last position will invite people to use a more specific answer as they'll encounter the more specific answers first)

Furthermore, I'm wondering what the difference between `animated=screen` and `advertising=screen` are. IMHO, `animated=screen` is now redundant and should be deprecated on the wiki as well

# Number of sides-question

At first glance, I'm also lost when I see the `From how many sides you can watch advertisments?`-question. Here some more guidance to a beginner would be welcome.

It seems to me that, if the type is 'poster box', then only '1' or '2' are valid answers.

For other features (e.g. a `totem` or a `flag), it seems to me that this question does not make sense, as you can see this feature from 360°.

Here, a `condition` might make sure that this question is only visible for applicable features.

**Comment by pietervdvn** [comment]
Please, don't let all my comments here discourage you! I know you put in a lot of work already, and the result is really nice already (I'm really fond of the theme ❤️ ), there are just a few small issues that would make it even better (and even more usable for a beginner).

**Comment by paunofu** [comment]
I think that all is finished or is near to finish, the only missing is the icons

**Comment by pietervdvn** [comment]
Here we go!

**Pull request merged**
