### PR TITLE
fireplace.json

### PR DESCRIPTION
**Pull request by Nukufel**
new theme for fireplaces (firepits and bbq)

### CODE REVIEW

**Comment by pietervdvn** [comment]
Great!

I see you also created two layers. Can you add those as file too in the repository, just like you did for the theme?

You'll also have to replace the link in the theme-config by the layer-id
Thanks!

**Comment by Nukufel** [comment]
Ok thx for the info.

I added the layers and changed the links to the ids in the theme config.

**Comment by pietervdvn** [comment]
Merged!

I made a few small improvements:

- I used a different icon for BBQ's and used a white circle as background
- I lowered the 'minzoom' from 12 to 8. There aren't that many items, so we can load them when more zoomed out
- I changed the 'seasonal'-question to be more specific. Instead of 'yes' and 'no', it now asks in which seasons it is available. (Technically, I reused the drinking_water question and moved it to be a 'builtin' question now)
- I removed the 'unknown'-option in some questions.

Good work though!

(It'll be available on https://dev.mapcomplete.org in about half an hour and on the main instance when I feel like updating)

**Comment by sfkeller** [comment]
Online now: https://mapcomplete.org/fireplace.html 
Thanks to Niklas and Pieter!

**Pull request merged**
