### PR TITLE
Prettify

### LINKED ISSUE #852: Introduce Prettier to the project
I started to like using https://prettier.io/ (with the [Tailwind Prettier Plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)) in all my projects. It takes a lot of mental load and save formatting time during development. And for a shared code base, it makes sure people format their contributions the same way.

In my opinion it would be a great addition to this project as well. What do others think?

---

Practically speaking, we would need to create one big "bring all files in line" commit. All future changes should then be formatted before commit, which could even be standardized [via Husky](https://prettier.io/docs/en/precommit.html#option-4-huskynethttpsgithubcomalirezanethuskynet) and CI checks.

### PR DESCRIPTION
**Pull request by eMerzh**
here is the prettify thing... 

i've also include a check and the cache for the CI

Fixes #852

### CODE REVIEW

**Comment by pietervdvn** [comment]
Hey,

Thank for the effort, but there are a few problems here which are gonna cause more problems down the line, especially because the current configuration is cleaning up automatically generated files. For these files, we should either switch the generator output or disable prettier for them.

For example: Docs/Layers/*.md are generated files. This means that prettier will change these again every time this documentation is regenerated.

Docs/Schemas and Docs/TagInfo have the same issues.

At last, the theme and layer-configuration files are rewritten by various scripts as well (especially the script synchronizing translations). In other words, prettier should not be needed for those files either.

**Comment by pietervdvn** [comment]
Second, I'm not very comfortable with merging such a huge PR. Breaking it down in smaller parts will allow for a gentle transition.

A good start might be to only reformat the .ts-files for now, then to move on to the series of files.

**Comment by eMerzh** [comment]
hey @pietervdvn 

ofc autogenerated shouldn't be formated... i've amend that.
let me know if i missed other directories
also i've format only ts files as you prefer... 
I don't think there will be issue with the files, but i understand that it's easier to grasp...  and the number of file changed is a bit scary 😅

**Comment by tordans** [comment]
I think this this will be a great improvement 👍 .

You could have a look at the [– deliberately few – config options](https://prettier.io/docs/en/options.html), @pietervdvn, to see if you like to adjust a few things. Just to make sure we do it now and don't need to reformat later.

In general, I find the defaults picket very good. I could, however, see two areas of change:
- [`printWidth`](https://prettier.io/docs/en/options.html#print-width), since the code uses very long names the code could look better; maybe `100`(?); probably something to compare for some file that has long method names.
- and then there is the indentation question. The repo uses 4 spaces ATM, right? The default is 2. One option that is promoted is to [use tabs](https://prettier.io/docs/en/options.html#tabs) instead… – [this issue](https://github.com/stylelint/stylelint/issues/4246) has a good discussion about it. Personally I would prefer a solution that allows 2 spaces for my setup (like having tabs + custom editor settings…). So I think the default of prettier is fine as well. However, there is a way out if you prefer the 4…

**Comment by eMerzh** [comment]
@tordans agree we probably need too carefully choose those… 
but... I would favor the less config ...
I'm in favor of 100 printWidth... but would keep the tabs away and leave two spaces as of now.

**Comment by pietervdvn** [comment]
Wow, an authentic tabs-vs-spaces-debate going on ;) Don't know if that was on my to-do-checklist or my to-don't-checklist... Personally, I'd rather keep those as much as they are now to keep the changes smaller, but I'll go with whatever is most common.

On a more serious note: I'm wondering what the best approach is to integrate prettier into the workflow, especially with respect to other contributors.

IMHO, the best would be to install it as a commit hook, so that prettier would run just before actually committing the files.
Second, it can also be incorporated in the 'housekeeping'-command, which is used to auto-update documentation and various other tasks.

**Comment by eMerzh** [comment]
ahah yes genuine tab vs space... after all i don't care as long as prettier is doing it for me :p 

to be honnest i think that prettier is one of the smallest barrier we have atm, but agree that putting more barriere is not something we want.
i'll remove the check then 👍  
and i'll try to add it to the housekeeping thing 🤔

**Comment by pietervdvn** [comment]
> and i'll try to add it to the housekeeping thing 

In 'package.json', search for 'housekeeping' and add it to the end of that command.

Yes, there are many barriers on starting to develop and no, prettier probably isn't the biggest one, but I'm always curious to hear which barriers you encountered.

**Comment by eMerzh** [comment]
yep updated 👍 

not sure i'll detail the whole thing here, but to name a few:
- not sure how to start, as a rooky i tried to clone then yarn && yarn start,  but that breaks everywhere (ofc....)
- the messages weren't that clear about what is going on
- then i found the guide... which """scares""" me with python3 install and stuff 🤔 
- then ofc as i already have a working JS env, i read the doc in diagonal, and miss the "init" thingy...
- after all is setup ... the time it take to launch (and the fact that it doesn't auto regernate) does not help
- and the custom "class based"  framework for the UI ins't really friendly... but that might be a matter of taste i guess?

**Comment by pietervdvn** [comment]
The repository used 4 spaces for indentation up till now, maybe we should keep this indentation as not to change too much? Unless there is a good reason to go to two spaces.

**Comment by eMerzh** [comment]
> The repository used 4 spaces for indentation up till now, maybe we should keep this indentation as not to change too much? Unless there is a good reason to go to two spaces.

no opinion on that... I'll change that  :)

**Comment by pietervdvn** [comment]
And maybe drop the ';' as well... I hardly use them and they are just extra noise to parse in many cases

**Comment by eMerzh** [comment]
> And maybe drop the ';' as well... I hardly use them and they are just extra noise to parse in many cases

ok, so drop ALL the  `;`  :) 

 btw sorry for the noise... battling a little bit with some oddities, but small fixes are coming

**Comment by pietervdvn** [comment]
Allright! Formatting looks pretty good now IMHO.

**Comment by pietervdvn** [comment]
In all honesty, I'm not entirely comfortable with merging so many changes at once. There are too many horror stories out there of someone sneaking in a cryptominer in this kind of PR's. 

Would you mind making a PR with _only_ the configuration files? I'll run the prettification then myself (after merging the TS-4 branch)

**Comment by eMerzh** [comment]
oh yeah ofc ... 
the format is easy once the config is in..

**Review by pietervdvn — APPROVED** [review]

**Pull request merged**
