### PR TITLE
AED theme - French translation

### PR DESCRIPTION
**Pull request by nlehuby**
I've tried to add the :fr: translation for the AED theme. Please let me know if it's the right way to do this.

### CODE REVIEW

**Comment by pietervdvn** [comment]
Yes, it is!

Thanks a lot, this is awesome!
I really appreciate this :)

**Comment by pietervdvn** [comment]
I've deployed it as well, you can select your language now in the AED-map.

**Comment by nlehuby** [comment]
Thanks, that's so cool :+1: 

BTW, you may need to update [the doc](https://github.com/pietervdvn/MapComplete#translating-mapcomplete), I spent lots of times looking at [this file](https://github.com/pietervdvn/MapComplete/blob/master/UI/i18n/Translations.ts) looking for the strings to translate for the AED theme :smile: 
I also did not manage to test my changes locally: when I follow the instructions from the [readme](https://github.com/pietervdvn/MapComplete#dev), I think it loads the bookcase theme only :thinking:

**Comment by pietervdvn** [comment]
Yeah, the docs should be improved. The new preset-system based on JSON-files is brand-new (like a week old), that is why.

**Pull request merged**
