### PR TITLE
Christmas theme

### PR DESCRIPTION
**Pull request by RobinLinde**
Adds a small theme, showing christmas trees, markets and shop selling christmas trees. Also fixes calculatedTags for AED theme.

[Demo](https://mapcomplete-git-feature-xmas-theme-robinlinde.vercel.app/xmas.html)

### CODE REVIEW

**Comment by pietervdvn** [comment]
While this is a really neat and fun theme, I'm a bit worried about the fact that christmas trees and christmas markets are -by definition- temporary events. This is a bit at odds with the 'no temporary objects' in OpenStreetMap.

Now, of course, it wouldn't be the first time that temporary objects are added into OSM and that the above rule is stretched, but I'm not entirely comfortable with simply merging and promoting this theme. A very obvious criticism we'll get is: "what will happen with those POI later on? Will the original mapper remove those?"

A possible fix is to add an expiry date (say: in march) to all objects created with MapComplete and then remove them all at once with a mechanical edit. For this, an end-date might be added into the presets.

**Comment by RobinLinde** [comment]
I'm gonna leave this as a branch on my fork for now, and I'll see later. Also when creating the theme I noticed some christmas features I mapped a few years ago, so definitely a real possibility. Most of the features are actually still here a few year later... I have split of the calculatedtags for AED layer into PR #1163

**Comment by tordans** [comment]
FYI, there is also a discussion about those `xmas` features in https://github.com/openstreetmap/id-tagging-schema/issues/721. Looks like next year they might have a move official status so a theme would be good marketing ;-). 

Last year there was a project to showcase open data that was good marketing for the team behind it https://www.technologiestiftung-berlin.de/blog/mit-offenen-daten-zum-weihnachtsmarkt-die-entwicklung-des-weihnachtsmarkt-finders https://weihnachtsmaerkte.odis-berlin.de

**Comment by miche101** [comment]
nice a tool to enter xmas features :)

**Pull request closed without merging**
