### PR TITLE
improved rendering

### PR DESCRIPTION
**Pull request by joostschouppe**
Colouring was also based on a field that has little meaning

@seppesantens, @sebkur or @chrneumann could you review and approve?

Just testing the workflow to be able to push small improvements online, even when @pietervdvn goes rollerskating again.

### CODE REVIEW

**Comment by sebkur** [comment]
I'm having a bit of trouble seeing what this is actually about. When I look at the theme, it looks like this:

aed

I cannot see any red circles anywhere, just the nice square SVG icons per defiblirator. I'm guessing that tag `Status=oud` is just not used currently on any of them and that is also why you removed that as a rule.

OK, in terms of workflow, can I easily test the effects of the changes (load the raw github json file from your branch in the main UI?)

**Comment by pietervdvn** [comment]
Hey @sebkur 

This is not a change to the AED-theme, but a change to the [AED_brugge-theme](https://mapcomplete.osm.be/aed_brugge), a custom theme where the dataset of the city of Bruges is loaded as well. An [intern](https://www.openstreetmap.org/user/Maarten%20O) is using it to check them all (and add them into OSM). When he is done, this theme will probably be removed again. It is also a small test case of how imports could be organized with MapComplete.

Anyway, I'm not approving this as I want this small change to be deployed _without my intervention_ to test the workflows ;)

**Comment by sebkur** [comment]
Ah, thanks for the clarification

**Comment by sebkur** [comment]
@joostschouppe you're changing the semanitics here a bit if I read the changes right. Before, points from the city dataset that were within a 25m distance of an OSM entry were shown in a transparent yellow. Those will be green now. All others will be red. Is that your intention?

**Comment by joostschouppe** [comment]
Yes @sebkur , that's exactly the point, I should have explained.
Before:
- yellow if near
- red if "old"
- green if "new"

But this "old" and "new" was just a thing I added for convenience when working in Excel, it is not important to the mapping.
So the distinction can be dropped.

The use-case for having the dots at all, is to see where OSM already has a nearby AED. Hence it makes more sense to simplify, and what says "yes" and "no" like green and red?! :)

**Review by sebkur — APPROVED** [review]
Looks good to me

**Comment by sebkur** [comment]
@joostschouppe if you prefer, I can merge and also deploy

**Comment by joostschouppe** [comment]
Yes, do merge it. Deployment should just be triggered automatically

**Comment by sebkur** [comment]
> Deployment should just be triggered automatically

ah, right, forgot about the homeserver

**Comment by pietervdvn** [comment]
Well, the homeserver died two days after I set it up to deploy automatically ;)

But deployment is now done neatly in a Github Action, so you can follow deploys live: https://github.com/pietervdvn/MapComplete/actions/runs/906753318

Btw, every branch is also deployed automatically on 'pietervdvn.github.io/mc/<branch-name>' now. If you want to do some easy experimentation, feel free to branch of from master and give it a spin.

**Comment by sebkur** [comment]
Cool, that is something very useful! Being able to test changes easily before pushing them to master was something I was hoping we could establish. Nice, it's already there!

**Pull request merged**
