### PR TITLE
Post partners and parcel lockers

### PR DESCRIPTION
**Pull request by RobinLinde**
Adds post partners and parcel lockers to the parcels theme. Also splits out the layers.

_**Post partners**_
- Operators (with some country-specific mappings)
- Services

_**Parcel lockers**_
- Renders both new and old style
- Brand (with some country-specific mappings)
- Operator
- Opening hours
- Reference number

_**Current issues**_
- [ ] No good way of adding post partners
- [ ] No way to upgrade tags of old-style parcel lockers (from [`amenity=vending_machine`](https://wiki.openstreetmap.org/wiki/Tag:vending=parcel%20pickup;parcel%20mail%20in) to [`amenity=parcel_locker`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparcel_locker)

### CODE REVIEW

**Comment by pietervdvn** [comment]
> No way to upgrade tags of old-style parcel lockers (from [amenity=vending_machine](https://wiki.openstreetmap.org/wiki/Tag:vending=parcel%20pickup;parcel%20mail%20in) to [amenity=parcel_locker](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparcel_locker)

To be honest, it is not the task of mapcomplete to systematically remap old tagging into new tagging. MapComplete users typically don't know anything about tags in the first place. Retagging would thus boil down to a distributed mechanical edit - in which case a global mechanical edit would be better.

**Comment by pietervdvn** [comment]
Maybe this PR can be split into two parts: one for the parcel-lockers (which are pretty straightforward on first sight) and could be merged without an extensive review.

**Comment by RobinLinde** [comment]
I've now split out the parcel lockers into #1033

**Comment by RobinLinde** [comment]
I think the version as it is now workable, doesn't feature any way of adding post partners, but still allows viewing them, as well as adding details to them.

**Review by pietervdvn — APPROVED** [review]

**Pull request merged**
