### PR TITLE
Add benches theme

### LINKED ISSUE #139: New theme: benches
Hi @pietervdvn,

I created a theme to help complete information about benches: https://tinyurl.com/y6leumxb
It uses quest icons from StreetComplete: [westnordost/StreetComplete@`v25.0-beta1`/res/graphics/quest icons](https://github.com/westnordost/StreetComplete/tree/v25.0-beta1/res/graphics/quest%20icons)

Would you be interested in including that theme in the repo?

```json
{
  "id": "benches",
  "title": {
    "en": "Benches",
    "de": "Sitzbänke"
  },
  "shortDescription": {},
  "description": {},
  "language": [
    "en",
    "de"
  ],
  "maintainer": "Florian Edelmann",
  "icon": "https://raw.githubusercontent.com/westnordost/StreetComplete/v25.0-beta1/res/graphics/quest%20icons/bench_poi.svg",
  "version": "1",
  "startLat": 0,
  "startLon": 0,
  "startZoom": 12,
  "widenFactor": 0.05,
  "socialImage": "",
  "layers": [
    {
      "id": "amenity=bench",
      "name": {
        "en": "Benches",
        "de": "Sitzbänke"
      },
      "minzoom": 14,
      "overpassTags": {
        "and": [
          "amenity=bench"
        ]
      },
      "title": {
        "render": {
          "en": "Bench",
          "de": "Sitzbank"
        },
        "mappings": []
      },
      "description": {},
      "tagRenderings": [
        {
          "render": {
            "en": "Backrest",
            "de": "Rückenlehne"
          },
          "freeform": {
            "key": "backrest",
            "addExtraTags": []
          },
          "mappings": [
            {
              "if": {
                "and": [
                  "backrest=yes"
                ]
              },
              "then": {
                "en": "Backrest: Yes",
                "de": "Rückenlehne: Ja"
              }
            },
            {
              "if": {
                "and": [
                  "backrest=no"
                ]
              },
              "then": {
                "en": "Backrest: No",
                "de": "Rückenlehne: Nein"
              }
            }
          ],
          "question": {
            "en": "Does this bench have a backrest?",
            "de": "Hat diese Bank eine Rückenlehne?"
          }
        },
        {
          "render": {
            "en": "{seats} seats",
            "de": "{seats} Sitzplätze"
          },
          "freeform": {
            "key": "seats",
            "type": "nat"
          },
          "mappings": [],
          "question": {
            "en": "How many seats does this bench have?",
            "de": "Wie viele Sitzplätze hat diese Bank?"
          }
        },
        {
          "render": {
            "en": "Material: {material}",
            "de": "Material: {material}"
          },
          "freeform": {
            "key": "material",
            "addExtraTags": []
          },
          "question": {
            "en": "What is the bench (seating) made from?",
            "de": "Aus welchem Material besteht die Sitzbank (Sitzfläche)?"
          }
        },
        {
          "render": {
            "en": "Color: {colour}",
            "de": "Farbe: {colour}"
          },
          "question": {
            "en": "Which color does this bench have?",
            "de": "Welche Farbe hat diese Sitzbank?"
          },
          "freeform": {
            "key": "colour"
          }
        }
      ],
      "hideUnderlayingFeaturesMinPercentage": 0,
      "icon": {
        "render": "https://raw.githubusercontent.com/westnordost/StreetComplete/v25.0-beta1/res/graphics/quest%20icons/bench_poi.svg",
        "mappings": []
      },
      "width": {
        "render": "8"
      },
      "iconSize": {
        "render": "20,20,center"
      },
      "color": {
        "render": "#00f"
      }
    },
    {
      "id": "bench=yes",
      "name": {
        "en": "Benches at public transport stops",
        "de": "Sitzbänke bei Haltestellen"
      },
      "minzoom": 14,
      "overpassTags": {
        "or": [
          "bench=yes",
          "bench=stand_up_bench"
        ]
      },
      "title": {
        "render": {
          "en": "Bench",
          "de": "Sitzbank"
        },
        "mappings": [
          {
            "if": {
              "or": [
                "public_transport=platform",
                "railway=platform",
                "highway=bus_stop"
              ]
            },
            "then": {
              "en": "Bench at public transport stop",
              "de": "Sitzbank bei Haltestelle"
            }
          },
          {
            "if": {
              "and": [
                "amenity=shelter"
              ]
            },
            "then": {
              "en": "Bench in shelter",
              "de": "Sitzbank in Unterstand"
            }
          }
        ]
      },
      "description": {},
      "tagRenderings": [
        {
          "render": {
            "en": "{name}",
            "de": "{name}"
          },
          "freeform": {
            "key": "name"
          }
        },
        {
          "render": {
            "en": "Stand up bench",
            "de": "Stehbank"
          },
          "freeform": {
            "key": "bench",
            "addExtraTags": []
          },
          "condition": {
            "and": [
              "bench=stand_up_bench"
            ]
          }
        }
      ],
      "hideUnderlayingFeaturesMinPercentage": 0,
      "icon": {
        "render": "https://raw.githubusercontent.com/westnordost/StreetComplete/v25.0-beta1/res/graphics/quest%20icons/bench_public_transport.svg"
      },
      "width": {
        "render": "8"
      },
      "iconSize": {
        "render": "20,20,center"
      },
      "color": {
        "render": "#00f"
      }
    }
  ],
  "roamingRenderings": []
}
```

### PR DESCRIPTION
**Pull request by FloEdelmann**
Closes #139.

### CODE REVIEW

**Comment by FloEdelmann** [comment]
I noticed that this OSMCha link doesn't work:

https://github.com/pietervdvn/MapComplete/blob/f7f81f5b2d922bc431177d9960a15ab318cef71f/README.md#L40

I manually entered the filter configuration there and saved it, which generated a link to share: https://osmcha.org/?aoi=f73496d7-81ed-4ca3-9d6b-78257a6d927e

Could you please check if it works also for you (or just in my account)? If so, I'll change the link in the README, too.

**Comment by pietervdvn** [comment]
Superdupercool! You even fixed typos in the README <3

The link to OSMCHA works for me, both on Firefox and Chromium (but it takes a bit to load). Which browser do you use? I suspect that the encoding breaks somewhere - so it might be better to change the link anyway.

**Comment by pietervdvn** [comment]
[The benches theme is live](https://pietervdvn.github.io/MapComplete/benches.html)!

**Comment by FloEdelmann** [comment]
Yay, thank you :)

Maybe it was just a hiccup, now the old link works for me, too :)

**Pull request merged**
