### PR TITLE
Maxspeed quest

### PR DESCRIPTION
**Pull request by yopaseopor**
Opening a pull request on MapComplete
=====================================

Hey! Thanks for opening a pull request on Mapcomplete! This probably means you want to add a new theme - if so, please
follow the checklist below. If this pull request is for some other issue, please ignore the template.

Adding your new theme
---------------------

Thanks for taking the time to create your theme and to add it to the main repository!

To making merging smooth, please make sure that each of the following conditions is met:

- [x] The codebase is GPL-licensed. By opening a pull request, the new theme will be GPL too
- [x] All images are included in the pull request and no images are loaded from an external service (e.g. Wikipedia)
- [ ] The [guidelines on how to make your own theme](https://github.com/pietervdvn/MapComplete/blob/master/Docs/Making_Your_Own_Theme.md)
  are read and followed

### CODE REVIEW

**Comment by pietervdvn** [comment]
@tordans Let's not run ahead of ourselves. First, this PR needs to be polished and merged in order to have a decent base to expand on. Once all of my feedback is handled, we can see from there.

**Comment by pietervdvn** [comment]
@yopaseopor 

Thanks for opening a pull request with a new theme!

First of all, congratulations on creating it - this isn't easy stuff.

At first sight, the big lines of the theme are good. However, there are still a whole heap of issues to address before I can pull in this theme.

# The formalities

## License of your theme

First of all, please make sure that you agree with the license under which your theme will be published, namely GPL. If you are fine with this, then check the corresponding box in the first comment of this PR.

## Some changes I made

I do have a script to do some cleanup automatically - which I ran and uploaded to your codebase. You'll notice a few changes, such as the addition of an `id` in each tagrendering and some legacy tags that got removed.

## Images

- [ ] You included a `.png` an `.svg` version of all the speeds. The themes _only_ use `.svg`- please remove all the `.png-files` and change all the `.png` in `.svg` (a search-and-replace in your favourite editor should handle this just fine)
- [ ] The names of your files are a bit cryptic: e.g. `ES_R301_10`. I suspect this stands for `ESpagna`, some code of traffic sign and the maxspeed. Maybe rename the `.svg`-files to something more descriptive, e.g. `maxspeed_10.svg`?
- [ ] What is the license of those images? Who made them? What is the source? Ideally, this is described in a `licenses.json` file next to the images.

**Comment by pietervdvn** [comment]
At last, this theme needs a 'units'-block, which indicates that a certain key should be interpreted as e.g. `km/h` or `mp/h` and which will add an option to choose from.

Please, [read the documentation for this here](https://github.com/pietervdvn/MapComplete/blob/e752c383612e26811812d2fb158acdf160f0b296/Models/ThemeConfig/Json/LayerConfigJson.ts#L355) - but feel free to reach out if you have questions. If something is unclear, the docs need updating.

**Comment by pietervdvn** [comment]
We are making progress!

Thanks for removing the pngs and updating the svgs.
I also noticed you added svgs for some other speeds. Please convert the text to a path, as using text might look different depending on which fonts the user has installed. For example, this is how it looks like on my machine: 

image

To fix this (I'm assuming you are using inkscape):
- Select the text you added
- Click Path (in the menu bar) > Object to Path
- Save

Apart from fixing this, you'll also need to update the regex detecting which images do exist.

**Comment by pietervdvn** [comment]
- [ ] You'll probably also want to enable splitting the road in smaller segments. For this, add `"allowSplit":true` in the layer configuration

**Comment by yopaseopor** [comment]
Excuse me, where I can put that piece of code? Thanks.

**Comment by pietervdvn** [comment]
Right above the 'tagRenderings' is an excellent place for the 'allowSplit'

**Pull request merged**
