### PR TITLE
Add dogs outside

### PR DESCRIPTION
**Pull request by Mannivu**
Add image and question for dogs=outside tag (to solve #1947)

### CODE REVIEW

**Review by pietervdvn — APPROVED** [review]

**Comment by pietervdvn** [comment]
Excellent! Even with an image :heart_eyes: 

Welcome aboard as contributor!

Your changes will be visible soon on dev.mapcomplete.org. It might take a while until I merge them in master.

**Comment by Mannivu** [comment]
Thank you!

**Comment by pietervdvn** [comment]
Hmmm, I've forgotten that all images should be attributed. Where did you find the image?

**Comment by Mannivu** [comment]
The dog is the one in [assets/layers/questions/dogs_allowed.svg](https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/questions/dogs_allowed.svg), the house I made it myself.

**Comment by pietervdvn** [comment]
Alright, I've assumed 'public domain': https://github.com/pietervdvn/MapComplete/blob/6549a5d10f1d739a9dbaeb074bd23863fe561dba/assets/layers/questions/license_info.json#L63

If you want attribution, I can change to a CC-BY license or similar.

**Comment by Mannivu** [comment]
No, PD it's good, don't worry about it.

**Pull request merged**
